version: "3"

services:
    php:
        container_name: "yemi-php"
        build:
            context: .
            dockerfile: Dockerfiles/php.dockerfile
        networks:
            - yemi
        volumes:
            - ./:/var/www/html

    nginx:
        container_name: "yemi-nginx"
        image: nginx:stable-alpine
        ports:
            - "8000:80"
        networks:
            - yemi
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


networks:
    yemi:
